name = "free-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "free-mail"
database_id = "60f0302a-1c2e-42d3-96ac-5119c5387998"

[[kv_namespaces]]
binding = "kv"
id = "free-mail"

[[r2_buckets]]
binding = "r2"
bucket_name = "free-mail2"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]


#[vars]
#orm_log = false
#domain = []				#邮件域名可配置多个 示例: ["example1.com","example2.com"]
#admin = ""				#管理员的邮箱	示例: admin@example.com
#jwt_secret = ""			#jwt令牌的密钥,随便填一串字符串
